# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fc3905f8a77637ce963cc7c939f40e7582ddc9ff2fca3511054adf3fb7f286ce611f0b1a00157f37021b0096535f75817e2f0d3aad576bc9532f8a03f65a7d9

test:
  secret_key_base: 396980c10e5763c30c2f8cb159d377d75c84ac3454954e0e06a8966dcaa9326857251ac6c15253d6bd0718986407ff1b03e02de578ef885d03f65cb96cec0113

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
